Demo9HealthbarScene.models = {
    hb1: {
        foreground: {
            top: 
            {"general":{"originalSize":{"x":10,"y":2},"size":{"x":10,"y":2},"zoom":10,"showGrid":false,"animated":false,"backgroundColor":"#000000"},"main":{"layers":[{"order":0,"id":"m_0","name":"","visible":true,"groups":[{"order":0,"type":"lines","strokeColor":"#FEF9F3","strokeColorOpacity":1,"fillColor":"#FF0000","fillColorOpacity":1,"closePath":false,"fill":false,"fillPattern":false,"visible":true,"clear":false,"id":"m_0_g_0","points":[{"point":{"x":0,"y":1},"order":0,"id":"m_0_g_0_p_0"},{"point":{"x":9,"y":1},"order":1,"id":"m_0_g_0_p_1"}]},{"order":1,"type":"lines","strokeColor":"#858A9D","strokeColorOpacity":1,"fillColor":"#FF0000","fillColorOpacity":1,"closePath":false,"fill":false,"fillPattern":false,"visible":true,"clear":false,"id":"m_0_g_1","points":[{"point":{"x":0,"y":0},"order":0,"id":"m_0_g_1_p_0"},{"point":{"x":9,"y":0},"order":1,"id":"m_0_g_1_p_1"}]}]}]}}
            ,
            bottom:
            {"general":{"originalSize":{"x":10,"y":2},"size":{"x":10,"y":2},"zoom":10,"showGrid":false,"animated":false,"backgroundColor":"#000000"},"main":{"layers":[{"order":0,"id":"m_0","name":"","visible":true,"groups":[{"order":0,"type":"lines","strokeColor":"#FEF9F3","strokeColorOpacity":1,"fillColor":"#FF0000","fillColorOpacity":1,"closePath":false,"fill":false,"fillPattern":false,"visible":true,"clear":false,"id":"m_0_g_0","points":[{"point":{"x":0,"y":0},"order":0,"id":"m_0_g_0_p_0"},{"point":{"x":9,"y":0},"order":1,"id":"m_0_g_0_p_1"}]},{"order":1,"type":"lines","strokeColor":"#858A9D","strokeColorOpacity":1,"fillColor":"#FF0000","fillColorOpacity":1,"closePath":false,"fill":false,"fillPattern":false,"visible":true,"clear":false,"id":"m_0_g_1","points":[{"point":{"x":0,"y":1},"order":0,"id":"m_0_g_1_p_0"},{"point":{"x":9,"y":1},"order":1,"id":"m_0_g_1_p_1"}]}]}]}}
            ,
            left: 
            {"general":{"originalSize":{"x":5,"y":20},"size":{"x":5,"y":20},"zoom":10,"showGrid":false,"animated":false,"backgroundColor":"#000000"},"main":{"layers":[{"order":0,"id":"m_0","name":"","visible":true,"groups":[{"order":0,"type":"lines","strokeColor":"#FEF9F3","strokeColorOpacity":1,"fillColor":"#FF0000","fillColorOpacity":1,"closePath":false,"fill":false,"fillPattern":false,"visible":true,"clear":false,"id":"m_0_g_0","points":[{"point":{"x":4,"y":18},"order":0,"id":"m_0_g_0_p_12"},{"point":{"x":3,"y":17},"order":1,"id":"m_0_g_0_p_13"},{"point":{"x":2,"y":16},"order":2,"id":"m_0_g_0_p_14"},{"point":{"x":2,"y":15},"order":3,"id":"m_0_g_0_p_15"},{"point":{"x":1,"y":14},"order":4,"id":"m_0_g_0_p_16"},{"point":{"x":1,"y":5},"order":5,"id":"m_0_g_0_p_17"},{"point":{"x":2,"y":4},"order":6,"id":"m_0_g_0_p_18"},{"point":{"x":2,"y":3},"order":7,"id":"m_0_g_0_p_19"},{"point":{"x":3,"y":2},"order":8,"id":"m_0_g_0_p_20"},{"point":{"x":4,"y":1},"order":9,"id":"m_0_g_0_p_21"}]},{"order":1,"type":"lines","strokeColor":"#858A9D","strokeColorOpacity":1,"fillColor":"#858A9D","fillColorOpacity":1,"closePath":false,"fill":false,"fillPattern":false,"visible":true,"clear":false,"id":"m_0_g_1","points":[{"point":{"x":4,"y":19},"order":0,"id":"m_0_g_1_p_0"},{"point":{"x":1,"y":16},"order":1,"id":"m_0_g_1_p_1"},{"point":{"x":1,"y":15},"order":2,"id":"m_0_g_1_p_2"},{"point":{"x":0,"y":14},"order":3,"id":"m_0_g_1_p_3"},{"point":{"x":0,"y":5},"order":4,"id":"m_0_g_1_p_4"},{"point":{"x":1,"y":4},"order":5,"id":"m_0_g_1_p_5"},{"point":{"x":1,"y":3},"order":6,"id":"m_0_g_1_p_6"},{"point":{"x":4,"y":0},"order":7,"id":"m_0_g_1_p_7"}]}]}]}}
            ,
            right: 
            {"general":{"originalSize":{"x":5,"y":20},"size":{"x":5,"y":20},"zoom":10,"showGrid":false,"animated":false,"backgroundColor":"#000000"},"main":{"layers":[{"order":0,"id":"m_0","name":"","visible":true,"groups":[{"order":0,"type":"lines","strokeColor":"#FEF9F3","strokeColorOpacity":1,"fillColor":"#FF0000","fillColorOpacity":1,"closePath":false,"fill":false,"fillPattern":false,"visible":true,"clear":false,"id":"m_0_g_0","points":[{"point":{"x":0,"y":1},"order":0,"id":"m_0_g_0_p_0"},{"point":{"x":2,"y":3},"order":1,"id":"m_0_g_0_p_1"},{"point":{"x":2,"y":4},"order":2,"id":"m_0_g_0_p_2"},{"point":{"x":3,"y":5},"order":3,"id":"m_0_g_0_p_3"},{"point":{"x":3,"y":14},"order":4,"id":"m_0_g_0_p_4"},{"point":{"x":2,"y":15},"order":5,"id":"m_0_g_0_p_5"},{"point":{"x":2,"y":16},"order":6,"id":"m_0_g_0_p_6"},{"point":{"x":0,"y":18},"order":7,"id":"m_0_g_0_p_7"}]},{"order":1,"type":"lines","strokeColor":"#858A9D","strokeColorOpacity":1,"fillColor":"#FF0000","fillColorOpacity":1,"closePath":false,"fill":false,"fillPattern":false,"visible":true,"clear":false,"id":"m_0_g_1","points":[{"point":{"x":0,"y":19},"order":0,"id":"m_0_g_1_p_0"},{"point":{"x":3,"y":16},"order":1,"id":"m_0_g_1_p_1"},{"point":{"x":3,"y":15},"order":2,"id":"m_0_g_1_p_2"},{"point":{"x":4,"y":14},"order":3,"id":"m_0_g_1_p_3"},{"point":{"x":4,"y":5},"order":4,"id":"m_0_g_1_p_4"},{"point":{"x":3,"y":4},"order":5,"id":"m_0_g_1_p_5"},{"point":{"x":3,"y":3},"order":6,"id":"m_0_g_1_p_6"},{"point":{"x":0,"y":0},"order":7,"id":"m_0_g_1_p_7"}]}]}]}}
        },
        background: {
            left: 
            {"general":{"originalSize":{"x":5,"y":20},"size":{"x":5,"y":20},"zoom":10,"showGrid":false,"animated":false,"backgroundColor":"#000000"},"main":{"layers":[{"order":0,"id":"m_0","name":"","visible":true,"groups":[{"order":0,"type":"lines","strokeColor":"#223256","strokeColorOpacity":1,"fillColor":"#223256","fillColorOpacity":1,"closePath":true,"fill":true,"fillPattern":false,"visible":true,"clear":false,"id":"m_0_g_0","points":[{"point":{"x":4,"y":19},"order":0,"id":"m_0_g_0_p_0"},{"point":{"x":1,"y":16},"order":1,"id":"m_0_g_0_p_1"},{"point":{"x":1,"y":15},"order":2,"id":"m_0_g_0_p_2"},{"point":{"x":0,"y":14},"order":3,"id":"m_0_g_0_p_3"},{"point":{"x":0,"y":5},"order":4,"id":"m_0_g_0_p_4"},{"point":{"x":1,"y":4},"order":5,"id":"m_0_g_0_p_5"},{"point":{"x":1,"y":3},"order":6,"id":"m_0_g_0_p_6"},{"point":{"x":4,"y":0},"order":7,"id":"m_0_g_0_p_7"}]}]}]}}
            ,
            right: 
            {"general":{"originalSize":{"x":5,"y":20},"size":{"x":5,"y":20},"zoom":10,"showGrid":false,"animated":false,"backgroundColor":"#000000"},"main":{"layers":[{"order":0,"id":"m_0","name":"","visible":true,"groups":[{"order":0,"type":"lines","strokeColor":"#223256","strokeColorOpacity":1,"fillColor":"#223256","fillColorOpacity":1,"closePath":true,"fill":true,"fillPattern":false,"visible":true,"clear":false,"id":"m_0_g_0","points":[{"point":{"x":0,"y":19},"order":0,"id":"m_0_g_0_p_0"},{"point":{"x":3,"y":16},"order":1,"id":"m_0_g_0_p_1"},{"point":{"x":3,"y":15},"order":2,"id":"m_0_g_0_p_2"},{"point":{"x":4,"y":14},"order":3,"id":"m_0_g_0_p_3"},{"point":{"x":4,"y":5},"order":4,"id":"m_0_g_0_p_4"},{"point":{"x":3,"y":4},"order":5,"id":"m_0_g_0_p_5"},{"point":{"x":3,"y":3},"order":6,"id":"m_0_g_0_p_6"},{"point":{"x":0,"y":0},"order":7,"id":"m_0_g_0_p_7"}]}]}]}},
            segment: 
            {"general":{"originalSize":{"x":10,"y":20},"size":{"x":10,"y":20},"zoom":10,"showGrid":false,"animated":false,"backgroundColor":"#000000"},"main":{"layers":[{"order":0,"id":"m_0","name":"","visible":true,"groups":[{"order":0,"type":"lines","strokeColor":"#223256","strokeColorOpacity":1,"fillColor":"#223256","fillColorOpacity":1,"closePath":true,"fill":true,"fillPattern":false,"visible":true,"clear":false,"id":"m_0_g_0","points":[{"point":{"x":0,"y":0},"order":0,"id":"m_0_g_0_p_8"},{"point":{"x":9,"y":0},"order":1,"id":"m_0_g_0_p_9"},{"point":{"x":9,"y":19},"order":2,"id":"m_0_g_0_p_10"},{"point":{"x":0,"y":19},"order":3,"id":"m_0_g_0_p_11"}]}]}]}}
        }
    }
}